Repository smd995/slowth, pull requests merged in 2025-05, with the labels that each got.

#3 [feature] ProgressBar 컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/components/atom/progressBar/index.tsx
Labels: feature

#6 [feature] Rating, RatingButton 컴포넌트 만들기
  package.json
  pnpm-lock.yaml
  src/components/atom/Rating/index.spec.tsx
  src/components/atom/Rating/index.tsx
  src/components/atom/RatingButton/index.spec.tsx
  src/components/atom/RatingButton/index.tsx
  src/components/icons/HeartIcons.tsx
  vitest.config.ts
  vitest.setup.ts
Labels: feature

#13 [feature] create LikeButton (찜하기 버튼)
  src/components/atom/likeButton/index.tsx
Labels: feature

#19 [feature] Chip 컴포넌트 구현
  src/components/atom/chip/index.tsx
Labels: feature

#39 feat: InformationContainer 1차
  src/components/atom/openConfirmedBadge/index.tsx
  src/components/atom/progressBar/index.tsx
  src/components/molecules/gatheringInformation/avatarList.tsx
  src/components/molecules/gatheringInformation/index.spec.tsx
  src/components/molecules/gatheringInformation/index.tsx
  src/components/molecules/gatheringInformation/participantInfo.tsx
  src/entity/gathering.ts
Labels: feature

#44 feature: reviewItem, reviewList 컴포넌트 구현 (#40)
  src/components/atom/Rating/index.tsx
  src/components/molecules/gatheringInformation/index.spec.tsx
  src/components/molecules/reviewItem/index.tsx
  src/components/organisms/reveiwList/index.tsx
  src/entity/review.ts
Labels: feature

#45 [refactor] Dropdown 스타일 및 기능 개선 (#43)
  src/components/atom/dropdown/index.tsx
Labels: refactor

#49 [refactor] Modal 컴포넌트 구조 및 위치 설정 개선 (#48)
  src/components/atom/modal/index.tsx
Labels: refactor

#51 [feature] Badge 컴포넌트 구현 (#50)
  src/components/atom/badge/index.tsx
Labels: feature

#59 [feature] Dropdown + Badge 개선 통합 PR (#57, #61)
  src/components/atom/badge/index.tsx
  src/components/atom/dropdown/index.tsx
Labels: feature

#60 chore: detail - fixture, msw setting (#58)
  .eslintcache
  .gitignore
  __tests__/cli/generate-reviews.ts
  __tests__/fixtures/detail-fixture.ts
  __tests__/generator/index.ts
  __tests__/mocks/browser.ts
  __tests__/mocks/handler/detail-handlers.ts
  __tests__/mocks/server.ts
  public/image/alt-place.jpg
  src/entity/review.ts
Labels: chore

#63 [feature] GNB 컴포넌트 구현 (#62)
  src/app/layout.tsx
  src/components/atom/logo/index.tsx
  src/components/atom/navItem/index.tsx
  src/components/icons/LogoIcon.tsx
  src/components/molecules/gnb/index.tsx
Labels: feature

#68 [feature] PageHeader 컴포넌트 구현 (#67)
  src/app/page.tsx
  src/components/icons/PageHeaderIcon.tsx
  src/components/molecules/pageHeader/index.tsx
Labels: feature

#74 [feature] Tabs 컴포넌트 아이콘 추가 및 스타일 개선 (#73)
  src/components/atom/tabs/index.tsx
  src/components/icons/MeditationIcon.tsx
  src/components/icons/VacationIcon.tsx
Labels: feature

#77 [style] global.css 컬러 변경 (#76)
  src/app/globals.css
  src/components/atom/likeButton/index.tsx
  src/components/atom/rating/index.tsx
  src/components/atom/ratingButton/index.tsx
  src/components/molecules/gnb/index.tsx
Labels: style

#82 fix: detail 오류 수정 (#80)
  src/app/detail/[id]/page.tsx
  src/components/molecules/gatheringInformation/index.spec.tsx
Labels: fix

#83 fix: ReviewsWithPagination 의존성 배열 관련 수정 (#80)
  src/components/molecules/gatheringInformation/avatarList.tsx
  src/components/organisms/ReviewsWithPagination/index.tsx
Labels: fix

#92 [feature] getGatheringList API 함수 구현 (#91)
  src/effect/gatherings/getGatheringList.ts
Labels: feature

#95 [Refactor] detail 페이지 관련 리팩토링
  src/app/detail/[id]/layout.tsx
  src/app/detail/[id]/not-found.tsx
  src/app/detail/[id]/page.tsx
  src/components/atom/likeButton/index.tsx
  src/components/atom/openConfirmedBadge/index.tsx
  src/components/atom/progressBar/index.tsx
  src/components/molecules/gatheringInformation/index.tsx
  src/effect/gatherings/getGatheringDetail.ts
  src/effect/like/index.ts
  src/effect/reviews/getReviews.ts
Labels: refactor
