Repository smd995/slowth, pull requests merged in 2025-06, with the labels that each got.

#106 [feature] GatheringList 페이지 SSR + 무한스크롤 구현
  package.json
  pnpm-lock.yaml
  src/app/GatheringListPage.tsx
  src/app/page.tsx
  src/components/molecules/gatheringCard/index.tsx
  src/effect/gatherings/getGatheringList.ts
Labels: feature

#109 [fix] GatheringCard 클릭 문제 및 코드 정리 (#108)
  src/app/GatheringListPage.tsx
  src/components/atom/likeButton/index.tsx
  src/components/molecules/gatheringCard/index.tsx
Labels: fix

#114 [feature] 필터 기능 개선(지역, 날짜, 정렬) 및 캘린더 컴포넌트 구현
  src/app/GatheringListPage.tsx
  src/components/molecules/calendar/index.tsx
  src/components/molecules/filterBar/index.tsx
  src/effect/gatherings/getGatheringList.ts
Labels: feature

#110 [Feature] gnb 기능 구현
  src/app/layout.tsx
  src/components/atom/likeButton/index.tsx
  src/components/atom/navItem/index.tsx
  src/components/molecules/gnb/index.tsx
  src/effect/like/index.ts
  src/stores/useLikeStore/index.ts
  src/stores/userStore/index.ts
Labels: feature

#112 [Feature] DeadlineTag 컴포넌트 구현 및 사용
  next.config.ts
  src/app/(detail)/gathering/[id]/layout.tsx
  src/app/(detail)/gathering/[id]/not-found.tsx
  src/app/(detail)/gathering/[id]/page.tsx
  src/components/atom/deadlineTag/index.tsx
  src/components/icons/ClockIcon.tsx
  src/components/molecules/gatheringCard/index.tsx
  src/effect/date/getDeadlineMessage.ts
Labels: feature

#116 [refactor] 상세페이지 폴더 구조 변경에 따른 라우팅 수정 (#115)
  src/app/GatheringListPage.tsx
Labels: refactor

#120 [refactor] 모임 찾기 페이지 개선 (#119)
  src/app/GatheringListPage.tsx
  src/components/atom/chip/index.tsx
  src/components/atom/dropdown/index.tsx
  src/components/molecules/filterBar/index.tsx
  src/components/molecules/gatheringCard/index.tsx
  src/components/molecules/pageHeader/index.tsx
  src/effect/gatherings/getGatheringList.ts
Labels: refactor

#125 [refactor] Dropdown, Calendar, FilterBar 개선 및 버그 수정 (#124)
  src/app/GatheringListPage.tsx
  src/components/atom/dropdown/index.tsx
  src/components/molecules/calendar/index.tsx
  src/components/molecules/filterBar/index.tsx
  src/components/molecules/gatheringCard/index.tsx
  src/components/molecules/gnb/index.tsx
Labels: refactor

#139 fix: 상세페이지 api 요청 관련 오류 수정 (axios client, toast 사용) (#117)
  src/components/molecules/bottomFloatingBar/bottomFloatingBarWrapper.tsx
  src/effect/gatherings/cancelGathering.ts
  src/effect/gatherings/checkIsJoined.ts
  src/effect/gatherings/getJoinedGatherings.ts
  src/effect/gatherings/joinGathering.ts
  src/effect/gatherings/leaveGathering.ts
Labels: fix

#141 [refactor] Calendar 컴포넌트 리팩토링 및 코드 구조 개선 (#140)
  src/app/globals.css
  src/app/page.tsx
  src/components/atom/timeColumn/index.tsx
  src/components/molecules/calendar/index.tsx
  src/components/molecules/calendarBody/index.tsx
  src/components/molecules/filterBar/index.tsx
  src/components/molecules/gatheringListPage/index.tsx
Labels: refactor

#149 [refactor] config 변경 및 디렉토리 변경 (#148)
  next.config.ts
  src/components/atom/deadlineTag/index.tsx
  src/components/organisms/ratingOverview/index.tsx
  src/libs/date/getDeadlineMessage.ts
  src/libs/formatScoreSummary.ts
Labels: refactor

#147 [refactor] API 환경변수 적용 및 이미지 최적화 (#146)
  src/components/molecules/gatheringCard/index.tsx
  src/effect/gatherings/getGatheringList.ts
Labels: refactor

#152 refactor: 정렬 옵션 수정 및 상수 정리 (#151)
  src/components/molecules/calendar/index.tsx
  src/components/molecules/gatheringListPage/index.tsx
Labels: refactor

#154 fix: 상세페이지 관련 에러 핸들링 (#153)
  src/app/(detail)/gathering/[id]/page.tsx
  src/components/atom/progressBar/index.tsx
  src/components/molecules/bottomFloatingBar/bottomFloatingBarWrapper.tsx
  src/components/molecules/gatheringCard/index.tsx
Labels: fix

#172 feature: mypage-myGatherings (#171)
  src/components/molecules/createdGatherings/index.tsx
  src/components/molecules/horizontalMyGatheringCard/index.tsx
  src/components/molecules/myGatherings/index.tsx
  src/components/molecules/tabContent/index.tsx
  src/components/molecules/verticalMyGatheringCard/index.tsx
  src/effect/gatherings/getCreatedGatherings.ts
  src/effect/gatherings/getMyGatherings.ts
  src/stores/gatheringStore.ts
Labels: feature

#174 [Refactor] 상세페이지 리팩토링 (swr 사용)
  package.json
  pnpm-lock.yaml
  src/app/(detail)/gathering/[id]/page.tsx
  src/app/layout.tsx
  src/components/molecules/bottomFloatingBar/bottomFloatingBarWrapper.tsx
  src/components/molecules/gatheringInformation/avatarList.tsx
  src/components/organisms/gatheringDetailPage/index.tsx
  src/effect/gatherings/getGatheringDetail.ts
  src/hooks/api/useGatheringDetail.ts
Labels: refactor

#175 refactor: detail (#173)
  src/app/(detail)/gathering/[id]/page.tsx
  src/components/molecules/gatheringInformation/participantInfo.tsx
  src/components/organisms/gatheringDetailPage/index.tsx
  src/components/skeleton/GatheringDetailSkeleton.tsx
Labels: refactor

#177 [refactor] 모임 찾기 리스트 초기 데이터, 필터, 정렬 등 로직 개선 (#176)
  src/app/page.tsx
  src/components/molecules/calendar/index.tsx
  src/components/molecules/filterBar/index.tsx
  src/components/molecules/gatheringCard/index.tsx
  src/components/molecules/gatheringCardSkeleton/index.tsx
  src/components/molecules/gatheringListPage/index.tsx
  src/constants/region.ts
  src/constants/sortOptions.ts
  src/effect/gatherings/getGatheringList.ts
Labels: refactor

#183 refactor: page Style (#182)
  src/app/(detail)/gathering/[id]/layout.tsx
  src/app/globals.css
  src/app/liked/page.tsx
  src/app/reviews/page.tsx
  src/components/molecules/gatheringListPage/index.tsx
  src/components/molecules/gnb/index.tsx
  src/components/organisms/gatheringDetailPage/index.tsx
  src/components/organisms/likedGatheringsPage/index.tsx
Labels: refactor

#185 fix: minor-fixes (#184)
  src/components/molecules/gatheringCard/index.tsx
  src/components/molecules/gatheringInformation/index.tsx
  src/components/molecules/gatheringInformation/participantInfo.tsx
  src/components/molecules/pageHeader/index.tsx
  src/constants/sortOptions.ts
  src/hooks/api/useLikedGatherings.ts
Labels: fix

#187 refactor: createGatheringModal (#186)
  src/components/atom/modal/index.tsx
  src/components/molecules/gatheringListPage/index.tsx
  src/components/organisms/createGatheringModalUI/index.tsx
  src/components/organisms/gatheringModal/index.tsx
  src/effect/gatherings/createGathering.ts
Labels: refactor

#191 feature: mypage-my-reviews (#190)
  src/components/molecules/createdGatherings/index.tsx
  src/components/molecules/myGatherings/index.tsx
  src/components/molecules/myReviews/index.tsx
  src/components/molecules/reviewModal/index.tsx
  src/components/molecules/tabContent/index.tsx
  src/components/organisms/myContentPage/index.tsx
  src/components/organisms/myReviewList/index.tsx
  src/effect/gatherings/getMyGatherings.ts
  src/effect/reviews/createReview.ts
  src/hooks/api/useCompletedGatherings.ts
  src/hooks/api/useCreatedGatherings.ts
  src/hooks/api/useMyGatherings.ts
  src/hooks/api/useUserReviews.ts
  src/stores/gatheringStore.ts
Labels: feature

#195 refactor: createGatheringModalUI-refactoring (#192)
  src/components/atom/customDateTime/index.tsx
  src/components/atom/customSelect/index.tsx
  src/components/atom/fileInput/index.tsx
  src/components/atom/input/index.tsx
  src/components/atom/select/index.tsx
  src/components/organisms/createGatheringModalUI/index.tsx
Labels: refactor

#199 Fix/filter date
  src/app/mypage/page.tsx
  src/app/reviews/page.tsx
  src/components/molecules/gatheringCard/index.tsx
  src/components/molecules/gatheringListPage/index.tsx
  src/components/molecules/verticalCreatedGatheringCard/index.tsx
  src/components/molecules/verticalMyGatheringCard/index.tsx
  src/components/molecules/verticalWritableReviewCard/index.tsx
  src/components/organisms/myContentPage/index.tsx
  src/hooks/api/useGatheringList.ts
Labels: fix
